# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
y = np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
y.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
type(y)

numpy.ndarray

6. Print the numpy version and the configuration


In [6]:
print((np.__version__),(np.show_config()))

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/P

7. Print the dimension of the array in question 3


In [7]:
print(y.ndim)

1


8. Create a boolean array with all the True values

In [8]:
bool_arr = np.random.choice([True], size=20)
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
d2 = np.arange(6).reshape(2,3)

10. Create a three dimensional array



In [10]:
d3 = np.arange(18).reshape(2,3,3)
print(d3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
z = y[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
I = np.ones((3,3))
print(I)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype('float32')
print(arr.dtype)

int32
float32


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1*arr2
print(arr1)
print(arr2)
print(arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1>arr2
print(arr1)
print(arr2)
print(arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
num = np.arange(10)
print(num[num%2==1])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [18]:
num[num%2==1] = -1
print(num)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
A = np.ones((5,5))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1][1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
AR2d = np.arange(10).reshape((2,5))
print(AR2d)
ARR2d = AR2d[0]
print("ans:", ARR2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ans: [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
AR2d = np.arange(10).reshape((2,5))
print(AR2d)
AR2dd = AR2d[1][1]
print("ans:", AR2dd)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ans: 6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
AR2d = np.arange(10).reshape((2,5))
print(AR2d)
ARR2d = AR2d[:,2]
print("ans:", ARR2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ans: [2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
randA = np.random.random((10,10))
print(randA)
xmin = randA.min() 
xmax = randA.max()
print("Min: ", xmin, "Max: ", xmax)

[[0.3696899  0.93499586 0.40505175 0.39648408 0.1680636  0.73267871
  0.71591309 0.42418699 0.97384558 0.41187142]
 [0.95118516 0.10851159 0.74167163 0.98271555 0.38655822 0.76041547
  0.87109315 0.43357122 0.75443361 0.51902594]
 [0.98371698 0.65225463 0.64187319 0.17202931 0.33526429 0.0133292
  0.00898095 0.05831899 0.24869516 0.36828907]
 [0.56047175 0.73747879 0.91448573 0.88499092 0.39670052 0.30860513
  0.72046387 0.07818027 0.81237968 0.24681629]
 [0.30037079 0.73282272 0.0770976  0.66746525 0.44248145 0.12187316
  0.66453195 0.28797204 0.85446372 0.79542304]
 [0.92189986 0.40032414 0.02828698 0.00242208 0.31473811 0.43366844
  0.07580235 0.89708633 0.43248965 0.52889522]
 [0.59729542 0.86172724 0.67665403 0.72514078 0.42478417 0.2477532
  0.42541622 0.79823282 0.3171088  0.06273664]
 [0.6782035  0.01791826 0.55774567 0.43282488 0.68037109 0.52115253
  0.99907836 0.68013014 0.61867837 0.08201598]
 [0.83487    0.17334913 0.79214826 0.8769778  0.0726663  0.63889121
  0.63603547 0

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b)) 

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(np.in1d(a,  b))[0])

[1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [53]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
Res = np.where(names != 'Will')
print(Res[0])
print(names[Res[0]])
print(data[Res[0],:])


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.94611278  1.77794322  0.50477985 -1.15821323]
 [ 1.02613128  0.50570252  1.86069335 -1.55551332]
 [ 0.31601133  0.01975194  0.1651338  -0.7542679 ]
 [ 0.62176075 -0.66854097  0.93060916 -0.95521587]
 [ 0.44139157  0.11394982 -0.7771174   1.15464351]
 [-0.37776499  0.90197871 -0.17312664 -1.71499801]
 [-0.95145371 -0.11632559 -0.75358344 -0.69874357]]
[0 1 3 5 6]
['Bob' 'Joe' 'Bob' 'Joe' 'Joe']
[[ 0.94611278  1.77794322  0.50477985 -1.15821323]
 [ 1.02613128  0.50570252  1.86069335 -1.55551332]
 [ 0.62176075 -0.66854097  0.93060916 -0.95521587]
 [-0.37776499  0.90197871 -0.17312664 -1.71499801]
 [-0.95145371 -0.11632559 -0.75358344 -0.69874357]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [89]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
Res = np.where(np.in1d(np.where(names != 'Will')[0],np.where(names != 'Joe')[0]))
print(Res[0])
print(names[Res[0]])
print(data[Res[0],:])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.28107335 -1.3157774  -1.48333609  1.27220413]
 [-1.10489406 -0.27928479  1.04809712 -0.43371139]
 [ 2.33510056 -0.81286072  0.69442649 -1.07275309]
 [-3.2370149   1.15833853 -1.05836522  0.77616038]
 [ 0.01904761 -0.46598482  0.58107548  0.98984439]
 [ 0.04740345 -0.62066033 -0.4975763  -0.68764095]
 [ 0.18207031 -0.97432973  0.08024863  0.92798717]]
[0 2]
['Bob' 'Will']
[[ 0.28107335 -1.3157774  -1.48333609  1.27220413]
 [ 2.33510056 -0.81286072  0.69442649 -1.07275309]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [71]:
ar2d = np.arange(1,16).reshape(5,3)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [75]:
arr2d = np.arange(1,17).reshape(2,2,4)
print(arr2d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [79]:
np.swapaxes(arr2d,0,2)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [81]:
sqr = np.arange(10)
sqrt = np.sqrt(sqr)
print(sqrt)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [92]:
A1 = np.random.randn(12)
A2 = np.random.randn(12)
A3 = np.maximum(A1,A2)
print(A1)
print(A2)
print(A3)

[ 1.33214066  0.13163692  0.9274155   0.99252469 -0.97998814  1.10289889
  0.20504068  0.90038832 -0.67709134  0.49967871 -0.04020192 -0.63722715]
[ 1.06139742  1.32728678  0.21401441 -0.01751816  1.11185723  1.18170703
 -0.33870011  0.33770305 -0.54374716 -0.07574914 -1.4585719   1.29524538]
[ 1.33214066  1.32728678  0.9274155   0.99252469  1.11185723  1.18170703
  0.20504068  0.90038832 -0.54374716  0.49967871 -0.04020192  1.29524538]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [94]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [97]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a, b))

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [101]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print (sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [105]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [109]:
xx = np.arange(20).reshape(4,5)
print(xx)
print(np.cumsum(xx))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
